package org.example.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T09:50:37.095-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/demo/", name = "HotelHiltonSystemServices")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelHiltonSystemServices {

    @WebMethod
    @RequestWrapper(localName = "consultarItinerarios", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.ConsultarItinerarios")
    @ResponseWrapper(localName = "consultarItinerariosResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.ConsultarItinerariosResponse")
    @WebResult(name = "itinerarios", targetNamespace = "")
    public java.util.List<org.example.demo.ConsultarItinerariosResponse.Itinerarios> consultarItinerarios(
        @WebParam(name = "fechaInicio", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaInicio,
        @WebParam(name = "fechaFinal", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaFinal,
        @WebParam(name = "ciudadOrigen", targetNamespace = "")
        java.lang.String ciudadOrigen,
        @WebParam(name = "ciudadDestino", targetNamespace = "")
        java.lang.String ciudadDestino
    );

    @WebMethod
    @RequestWrapper(localName = "realizarReserva", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.RealizarReserva")
    @ResponseWrapper(localName = "realizarReservaResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.RealizarReservaResponse")
    public void realizarReserva(
        @WebParam(mode = WebParam.Mode.INOUT, name = "fechaIngreso", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaIngreso,
        @WebParam(mode = WebParam.Mode.INOUT, name = "fechaSalida", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaSalida,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ciudad", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ciudad,
        @WebParam(mode = WebParam.Mode.INOUT, name = "hotel", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hotel,
        @WebParam(mode = WebParam.Mode.INOUT, name = "habitacion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> habitacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "idReserva", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "idHabitacion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> idHabitacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "motivoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> motivoEstado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaRespuesta", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigoEstado
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerReserva", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.ObtenerReserva")
    @ResponseWrapper(localName = "obtenerReservaResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.ObtenerReservaResponse")
    public void obtenerReserva(
        @WebParam(mode = WebParam.Mode.INOUT, name = "idReserva", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "idHabitacion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> idHabitacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaIngreso", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaIngreso,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaSalida", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaSalida,
        @WebParam(mode = WebParam.Mode.OUT, name = "ciudad", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ciudad,
        @WebParam(mode = WebParam.Mode.OUT, name = "hotel", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> hotel,
        @WebParam(mode = WebParam.Mode.OUT, name = "habitacion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> habitacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "motivoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> motivoEstado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaRespuesta", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigoEstado
    );

    @WebMethod
    @RequestWrapper(localName = "cancelarReserva", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.CancelarReserva")
    @ResponseWrapper(localName = "cancelarReservaResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.CancelarReservaResponse")
    public void cancelarReserva(
        @WebParam(name = "idReserva", targetNamespace = "")
        java.lang.String idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "motivoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> motivoEstado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaRespuesta", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigoEstado
    );
}
