package org.example.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T09:50:37.133-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "HotelHiltonService",
                  wsdlLocation = "file:/D:/oxygen/eclipse-workspace/HotelHiltonSOAPService/src/main/resources/wsdl/hotelhilton.wsdl",
                  targetNamespace = "http://www.example.org/demo/")
public class HotelHiltonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/demo/", "HotelHiltonService");
    public final static QName HotelHiltonServicesEndpoint = new QName("http://www.example.org/demo/", "HotelHiltonServicesEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/oxygen/eclipse-workspace/HotelHiltonSOAPService/src/main/resources/wsdl/hotelhilton.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelHiltonService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/oxygen/eclipse-workspace/HotelHiltonSOAPService/src/main/resources/wsdl/hotelhilton.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelHiltonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelHiltonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelHiltonService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HotelHiltonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelHiltonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelHiltonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HotelHiltonSystemServices
     */
    @WebEndpoint(name = "HotelHiltonServicesEndpoint")
    public HotelHiltonSystemServices getHotelHiltonServicesEndpoint() {
        return super.getPort(HotelHiltonServicesEndpoint, HotelHiltonSystemServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelHiltonSystemServices
     */
    @WebEndpoint(name = "HotelHiltonServicesEndpoint")
    public HotelHiltonSystemServices getHotelHiltonServicesEndpoint(WebServiceFeature... features) {
        return super.getPort(HotelHiltonServicesEndpoint, HotelHiltonSystemServices.class, features);
    }

}
